/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RandomMlbTeamGeneratorRouteImport } from './routes/random-mlb-team-generator'
import { Route as RandomNbaTeamGeneratorRouteImport } from './routes/random-nba-team-generator'
import { Route as RandomNflTeamGeneratorRouteImport } from './routes/random-nfl-team-generator'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomMlbTeamGeneratorRoute = RandomMlbTeamGeneratorRouteImport.update({
  id: '/random-mlb-team-generator',
  path: '/random-mlb-team-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomNbaTeamGeneratorRoute = RandomNbaTeamGeneratorRouteImport.update({
  id: '/random-nba-team-generator',
  path: '/random-nba-team-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomNflTeamGeneratorRoute = RandomNflTeamGeneratorRouteImport.update({
  id: '/random-nfl-team-generator',
  path: '/random-nfl-team-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/random-mlb-team-generator': typeof RandomMlbTeamGeneratorRoute
  '/random-nba-team-generator': typeof RandomNbaTeamGeneratorRoute
  '/random-nfl-team-generator': typeof RandomNflTeamGeneratorRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/random-mlb-team-generator': typeof RandomMlbTeamGeneratorRoute
  '/random-nba-team-generator': typeof RandomNbaTeamGeneratorRoute
  '/random-nfl-team-generator': typeof RandomNflTeamGeneratorRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/random-mlb-team-generator': typeof RandomMlbTeamGeneratorRoute
  '/random-nba-team-generator': typeof RandomNbaTeamGeneratorRoute
  '/random-nfl-team-generator': typeof RandomNflTeamGeneratorRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/random-mlb-team-generator'
    | '/random-nba-team-generator'
    | '/random-nfl-team-generator'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/random-mlb-team-generator'
    | '/random-nba-team-generator'
    | '/random-nfl-team-generator'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/random-mlb-team-generator'
    | '/random-nba-team-generator'
    | '/random-nfl-team-generator'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RandomMlbTeamGeneratorRoute: typeof RandomMlbTeamGeneratorRoute
  RandomNbaTeamGeneratorRoute: typeof RandomNbaTeamGeneratorRoute
  RandomNflTeamGeneratorRoute: typeof RandomNflTeamGeneratorRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-mlb-team-generator': {
      id: '/random-mlb-team-generator'
      path: '/random-mlb-team-generator'
      fullPath: '/random-mlb-team-generator'
      preLoaderRoute: typeof RandomMlbTeamGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-nba-team-generator': {
      id: '/random-nba-team-generator'
      path: '/random-nba-team-generator'
      fullPath: '/random-nba-team-generator'
      preLoaderRoute: typeof RandomNbaTeamGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-nfl-team-generator': {
      id: '/random-nfl-team-generator'
      path: '/random-nfl-team-generator'
      fullPath: '/random-nfl-team-generator'
      preLoaderRoute: typeof RandomNflTeamGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RandomMlbTeamGeneratorRoute: RandomMlbTeamGeneratorRoute,
  RandomNbaTeamGeneratorRoute: RandomNbaTeamGeneratorRoute,
  RandomNflTeamGeneratorRoute: RandomNflTeamGeneratorRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
